services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${TARGET_DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-storage:/var/lib/mysql
      - ./.initdb:/docker-entrypoint-initdb.d

volumes:
  db-storage:
